# Generated by Django 6.0.3 on 2026-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_otplog_booking_amount_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
    ]
